package config

const tomlTemplate = `# Protheon Configuration
# Lines starting with '#' are comments.
# Remove comments and adjust values as needed

# Path to a Lua file to apply several mappings to the input
# Note: The input is generally passed through a global table called 'record'
# transformations = "./transform.lua"

# Input data source, e.g., json, jsonl, csv file
# [input]
# Path to the input data source
# path = "./users.jsonl"
# Extension of the data source
# extension = "jsonl"
# Any compression algorithm to be aware of
# compress = "zstd"

# Target datasource connection
# [datasource]
# Fully qualified database URL
# url = "postgres://user:password@localhost:5432/mydb?sslmode=disable"
# Target database table
# table = "user"
#
# ---
# This file was auto-generated by Protheon.
# It is safe to edit while the program is not running.
`

const yamlTemplate = `# Protheon Configuration
# Lines starting with '#' are comments
# Remove comments and adjust values as needed

# Path to a Lua file to apply several mappings to the input
# Note: The input is generally passed through a global table called 'record'
# transformations: "./transform.lua"

# Input data source, e.g., json, jsonl, csv file
# input:
#	  Path to the input data source
#   path: "./users.jsonl"
#   Extension of the data source
#   extension: "jsonl"
#   Any compression algorithm to be aware of
#   compress: "zstd" 

# Target datasource connection
# datasource:
#   Fully qualified database URL 
#   url: "postgres://user:password@localhost:5432/mydb?sslmode=disable"
#   Target database table
#   table: "user"
#
# ---
# This file was auto-generated by Protheon.
# It is safe to edit while the program is not running.
`
