name: Create Release

on:
  push:
    tags:
      - v[0-9]*.[0-9]*.[0-9]*(-*)*

permissions:
  contents: write

jobs:
  create-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run Makefile build
        run: |
          make clean
          make release

      # Requires permissions
      - name: Create Github Release
        uses: softprops/actions-gh-release@v2
        with:
          files: bin/**
          name: Protheon v${{ github.ref }}
          body: "Automated Protheon release"
          prerelease: true
